In [1]:
import pandas as pd
import numpy as np


tournaments = pd.read_csv('merged_tournaments_1_150_added_missed_links.csv')
tournaments

,Unnamed: 0,white_name,white_link,white_rating,white_title,black_name,black_link,black_rating,black_title,result_white,result_black,date,round,pairings,game_link,accuracy_white,accuracy_black,links
0,0,Hikaru,https://www.chess.com/member/hikaru,3426,GM,MagnusCarlsen,https://www.chess.com/member/magnuscarlsen,3377,GM,0.5,0.5,2024-11-19 08:00:00,10,1.0,https://www.chess.com/game/live/125777401099,97.69,97.68,https://www.chess.com/analysis/game/live/12577...
1,1,mishanick,https://www.chess.com/member/mishanick,3188,GM,VladimirKramnik,https://www.chess.com/member/vladimirkramnik,3062,GM,1.0,0.0,2024-11-19 08:00:00,10,1.0,https://www.chess.com/game/live/125777401103,82.56,80.45,https://www.chess.com/analysis/game/live/12577...
2,2,lachesisQ,https://www.chess.com/member/lachesisq,3225,GM,Volodar_Murzin,https://www.chess.com/member/volodar_murzin,3178,GM,1.0,0.0,2024-11-19 08:00:00,10,1.0,https://www.chess.com/game/live/125777401107,88.62,83.78,https://www.chess.com/analysis/game/live/12577...
3,3,jefferyx,https://www.chess.com/member/jefferyx,3149,GM,AnishOnYoutube,https://www.chess.com/member/anishonyoutube,3072,GM,1.0,0.0,2024-11-19 08:00:00,10,1.0,https://www.chess.com/game/live/125777401109,75.96,71.06,https://www.chess.com/analysis/game/live/12577...
4,4,Shankland,https://www.chess.com/member/shankland,3022,GM,ChristopherYoo,https://www.chess.com/member/christopheryoo,3155,GM,0.5,0.5,2024-11-19 08:00:00,10,1.0,https://www.chess.com/game/live/125777401113,98.44,98.87,https://www.chess.com/analysis/game/live/12577...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321103,321103,VTB-81,https://www.chess.com/member/vtb-81,2097,CM,Iulian22,https://www.chess.com/member/iulian22,2435,CM,1.0,0.0,2024-12-31 14:00:00,11,4.0,https://www.chess.com/game/live/129428006249,NaN,NaN,https://www.chess.com/analysis/game/live/12942...
321104,321104,PNEPaul,https://www.chess.com/member/pnepaul,1983,NM,pushingsomepieces,https://www.chess.com/member/pushingsomepieces,2242,WFM,0.5,0.5,2024-12-31 14:00:00,11,4.0,https://www.chess.com/game/live/129428006253,NaN,NaN,https://www.chess.com/analysis/game/live/12942...
321105,321105,NWCapa,https://www.chess.com/member/nwcapa,1940,NM,protectiago,https://www.chess.com/member/protectiago,1956,NM,1.0,0.0,2024-12-31 14:00:00,11,4.0,https://www.chess.com/game/live/129428006255,NaN,NaN,https://www.chess.com/analysis/game/live/12942...
321106,321106,boguszp,https://www.chess.com/member/boguszp,2002,CM,charlescandycampbell,https://www.chess.com/member/charlescandycampbell,2336,CM,0.0,1.0,2024-12-31 14:00:00,11,4.0,https://www.chess.com/game/live/129428006257,NaN,NaN,https://www.chess.com/analysis/game/live/12942...
321107,321107,Goughfather,https://www.chess.com/member/goughfather,2020,CM,NMChessToImpress,https://www.chess.com/member/nmchesstoimpress,2277,NM,0.0,1.0,2024-12-31 14:00:00,11,4.0,https://www.chess.com/game/live/129428006259,NaN,NaN,https://www.chess.com/analysis/game/live/12942...

# Adding missed links

In [2]:
scraped_accuracy_1 = pd.read_csv('scrape_outputs_second_iteration/worker_0_checkpoint_40660.csv')
scraped_accuracy_2 = pd.read_csv('scrape_outputs_second_iteration/worker_0_checkpoint_53505_reverse.csv')

In [3]:
scraped_accuracy_1 = scraped_accuracy_1[scraped_accuracy_1['ok'] == True][['links', 'accuracy1', 'accuracy2']].reset_index(drop=True).rename(columns={'accuracy1': 'accuracy_white', 'accuracy2': 'accuracy_black'})
scraped_accuracy_2 = scraped_accuracy_2[scraped_accuracy_2['ok'] == True][['links', 'accuracy1', 'accuracy2']].reset_index(drop=True).rename(columns={'accuracy1': 'accuracy_white', 'accuracy2': 'accuracy_black'})
scraped_accuracy = pd.concat([scraped_accuracy_1, scraped_accuracy_2]).reset_index(drop=True)
scraped_accuracy

,links,accuracy_white,accuracy_black
0,https://www.chess.com/analysis/game/live/12577...,79.6,85.1
1,https://www.chess.com/analysis/game/live/12577...,94.5,80.3
2,https://www.chess.com/analysis/game/live/12577...,83.2,85.1
3,https://www.chess.com/analysis/game/live/12577...,98.4,86.8
4,https://www.chess.com/analysis/game/live/12577...,84.1,89.6
...,...,...,...
87851,https://www.chess.com/analysis/game/live/11853...,86.3,85.2
87852,https://www.chess.com/analysis/game/live/11853...,87.6,79.4
87853,https://www.chess.com/analysis/game/live/11853...,91.9,85.2
87854,https://www.chess.com/analysis/game/live/11853...,88.2,92.4
87855,https://www.chess.com/analysis/game/live/11853...,77.3,90.3

In [4]:
tournaments = tournaments.merge(
    scraped_accuracy[['links', 'accuracy_white', 'accuracy_black']],
    on='links',
    how='left',
    suffixes=('', '_new')
)

tournaments['accuracy_white'] = tournaments['accuracy_white'].fillna(tournaments['accuracy_white_new'])
tournaments['accuracy_black'] = tournaments['accuracy_black'].fillna(tournaments['accuracy_black_new'])

tournaments = tournaments.drop(columns=['accuracy_white_new', 'accuracy_black_new'])

In [5]:
tournaments

,Unnamed: 0,white_name,white_link,white_rating,white_title,black_name,black_link,black_rating,black_title,result_white,result_black,date,round,pairings,game_link,accuracy_white,accuracy_black,links
0,0,Hikaru,https://www.chess.com/member/hikaru,3426,GM,MagnusCarlsen,https://www.chess.com/member/magnuscarlsen,3377,GM,0.5,0.5,2024-11-19 08:00:00,10,1.0,https://www.chess.com/game/live/125777401099,97.69,97.68,https://www.chess.com/analysis/game/live/12577...
1,1,mishanick,https://www.chess.com/member/mishanick,3188,GM,VladimirKramnik,https://www.chess.com/member/vladimirkramnik,3062,GM,1.0,0.0,2024-11-19 08:00:00,10,1.0,https://www.chess.com/game/live/125777401103,82.56,80.45,https://www.chess.com/analysis/game/live/12577...
2,2,lachesisQ,https://www.chess.com/member/lachesisq,3225,GM,Volodar_Murzin,https://www.chess.com/member/volodar_murzin,3178,GM,1.0,0.0,2024-11-19 08:00:00,10,1.0,https://www.chess.com/game/live/125777401107,88.62,83.78,https://www.chess.com/analysis/game/live/12577...
3,3,jefferyx,https://www.chess.com/member/jefferyx,3149,GM,AnishOnYoutube,https://www.chess.com/member/anishonyoutube,3072,GM,1.0,0.0,2024-11-19 08:00:00,10,1.0,https://www.chess.com/game/live/125777401109,75.96,71.06,https://www.chess.com/analysis/game/live/12577...
4,4,Shankland,https://www.chess.com/member/shankland,3022,GM,ChristopherYoo,https://www.chess.com/member/christopheryoo,3155,GM,0.5,0.5,2024-11-19 08:00:00,10,1.0,https://www.chess.com/game/live/125777401113,98.44,98.87,https://www.chess.com/analysis/game/live/12577...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321103,321103,VTB-81,https://www.chess.com/member/vtb-81,2097,CM,Iulian22,https://www.chess.com/member/iulian22,2435,CM,1.0,0.0,2024-12-31 14:00:00,11,4.0,https://www.chess.com/game/live/129428006249,93.70,79.00,https://www.chess.com/analysis/game/live/12942...
321104,321104,PNEPaul,https://www.chess.com/member/pnepaul,1983,NM,pushingsomepieces,https://www.chess.com/member/pushingsomepieces,2242,WFM,0.5,0.5,2024-12-31 14:00:00,11,4.0,https://www.chess.com/game/live/129428006253,88.80,87.30,https://www.chess.com/analysis/game/live/12942...
321105,321105,NWCapa,https://www.chess.com/member/nwcapa,1940,NM,protectiago,https://www.chess.com/member/protectiago,1956,NM,1.0,0.0,2024-12-31 14:00:00,11,4.0,https://www.chess.com/game/live/129428006255,87.20,80.90,https://www.chess.com/analysis/game/live/12942...
321106,321106,boguszp,https://www.chess.com/member/boguszp,2002,CM,charlescandycampbell,https://www.chess.com/member/charlescandycampbell,2336,CM,0.0,1.0,2024-12-31 14:00:00,11,4.0,https://www.chess.com/game/live/129428006257,81.30,92.80,https://www.chess.com/analysis/game/live/12942...
321107,321107,Goughfather,https://www.chess.com/member/goughfather,2020,CM,NMChessToImpress,https://www.chess.com/member/nmchesstoimpress,2277,NM,0.0,1.0,2024-12-31 14:00:00,11,4.0,https://www.chess.com/game/live/129428006259,87.00,94.20,https://www.chess.com/analysis/game/live/12942...

In [7]:
new_links = tournaments[(tournaments['accuracy_white'].isna()) & (tournaments['accuracy_black'].isna())].reset_index(drop=True)['links']

In [8]:
new_links.to_csv('new_missed_links_2026_third_iteration.csv')

In [10]:
tournaments.to_csv('merged_tournaments_1_150_added_missed_links_2.csv', index=False)